# Generated by Django 4.2.1 on 2023-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('ap_paterno', models.CharField(max_length=20)),
                ('ap_materno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('usuario_alum', models.CharField(max_length=20, unique=True)),
                ('contrasena_alum', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombre_prof', models.CharField(max_length=20)),
                ('s_nombre_prof', models.CharField(max_length=20)),
                ('ap_paterno_prof', models.CharField(max_length=20)),
                ('ap_materno_prof', models.CharField(max_length=20)),
                ('email_prof', models.CharField(max_length=30)),
                ('usuario_prof', models.CharField(max_length=20)),
                ('contrasena_prof', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
    ]
