# Generated by Django 4.2.1 on 2023-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaAlum',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'asignatura_alum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignaturaProf',
            fields=[
                ('id_asign_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asign_prof', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'asignatura_prof',
                'managed': False,
            },
        ),
    ]
